### ISSUE TITLE
Object doesn't support property or method 'blur'

### ISSUE THREAD

**Issue by kumarharsh** [airbnb/react-dates#1097]
This occurs on Edge if an SVG element is the `document.activeElement`. This library tries to call `document.activeElement.blur()` and SVG elements don't have a blur property defined in Edge, causing an error.

![image](https://user-images.githubusercontent.com/760112/38237547-26285b0e-3745-11e8-8763-e3b375336873.png)

**Comment by ljharb** [comment]
This sounds like both something that is a bug with us and also with edge. Have you filed a bug on chakracore/edge?

**Comment by xiaotian-tan** [comment]
I tried with react-dates demo site on IE 11, and it definitely has a bug.

**Comment by majapw** [comment]
Huh, I wonder if this is due to the restructuring of the navigation. I think a simple patch would be to check for the blur element. Let me put up a PR.

**Comment by majapw** [comment]
Yup, okay sorry for the delay! I am working on a fix now. :)

**Comment by majapw** [comment]
Fixed in v18! :)

**Comment by xiaotian-tan** [comment]
Yeah! Thanks a lot 👍

**Comment by markhaasjes** [comment]
I've updated the react-dates library to version `18.1.0` and I still see this issue when clicking on the month navigation "arrow" itself, when clicking on the button it works fine. I've reproduced this issue in IE11 while using BrowserStack.
