### ISSUE TITLE
Blinking cursor in mobile

### ISSUE THREAD

**Issue by narmadham** [airbnb/react-dates#253]
Hi,

I am using SingleDatePicker with portal option. Once the portal is closed the focused sets back to the input again. It doesnt create a problem in desktop but in mobile I am gettting a blinking cursor. I am able to replicate in the examples as well.

Is there any way to avoid the blinking cursor ?

**Comment by jonathanong** [comment]
I am seeing the same issue and it is messing up my vertical mobile layout. here's what happens immediately after clicking a date input:

![img_0218](https://cloud.githubusercontent.com/assets/643505/22051727/11932e54-dcfa-11e6-9104-38c5a618d0ec.PNG)

I can only get the correct layout when pressing "done"

**Comment by jonathanong** [comment]
this may relevant to https://github.com/airbnb/react-dates/issues/246

**Comment by narmadham** [comment]
Hi @jonathanong  Ya it is almost similar. I tried blurring out after date change but no luck. Reconsidering the usage of this plugin since there are lot of minor issues which are creating an impact.

**Comment by amlivingamliving** [comment]
Hi @jonathanong and @narmadham  - I'm having the same issue. It does look similar to #246 . This is with `withPortal` set to `true` on my `SingleDatePickerWrapper`.

![img_9606](https://cloud.githubusercontent.com/assets/8516645/22128103/eece5a5a-de53-11e6-99f9-6bb891efff4c.PNG)

**Comment by jurekbarth** [comment]
I think its a bug with the `readonly` attribute on an input field. Safari iOS still triggers focus even if `readonly` is set. 
You can test yourself here: http://codepen.io/jurekbarth/pen/PWpEQv

**Comment by jurekbarth** [comment]
For a temporary workaround you could set the disabled attribute like so `disabled={disabled || this.isTouchDevice}` in `DateInput.jsx`

**Comment by dominicchapman** [comment]
@jurekbarth it looks like a change was made back in November having been tested on Surface Tablet, not iOS https://github.com/airbnb/react-dates/pull/174

**Comment by narmadham** [comment]
thanks @jurekbarth this workaround really helped me.

**Comment by Nehlin** [comment]
@jurekbarth Not getting the workaround to work. It's setting the disabled flag to true permanently for ios, right? If so how does that help?

**Comment by jurekbarth** [comment]
@Nehlin how are you trying to solve it? Did you change the file in your `node_modules` folder? If so thats not the way to go, because your bundler catch up the already processed file in the `lib` folder. Hope this helps :)

**Comment by majapw** [comment]
This should be fixed in v6.0.2! (Hopefully)

**Comment by jurekbarth** [comment]
@majapw Sure now it's not blinking anymore, but it's still not working as expected.

Thats how it looks like with the fix applied. You still have to click "Done" or in German "Fertig" to get things working properly.
![img_0024](https://cloud.githubusercontent.com/assets/4249843/22734496/30b47632-edf6-11e6-8ac6-6320114da860.PNG)

The desired outcome would be:
![img_0025](https://cloud.githubusercontent.com/assets/4249843/22734583/82ddc0c6-edf6-11e6-8609-4440a8ee1cc6.PNG)

It's an iOS Bug :/ Is there some hacky way to just detect iOS devices?

**Comment by majapw** [comment]
@moonboots what kind of device were you testing on?

There's def hacky ways to detect iOS and we can go there if that's necessary, but I don't know if this happens on all iOS devices even. What version of iOS/Safari are you using?

**Comment by moonboots** [comment]
I'm on an iphone with iOS 10. In the datepicker setup we're working on, the "Done" button still appears but doesn't throw off the layout or behavior. @jurekbarth, in your example, is `focusedInput` set to null after a user taps a date? If the desired behavior is closing the portal/SingleDatePicker after date selection, `this.setState({ focsedInput: null });` should remove lingering focus.

@majapw We could consider swapping `<input>` tags with `<div>` on touch devices. However, there are probably accessibility concerns we'd need to address.

**Comment by NickTiut** [comment]
@majapw I also get the same behaviour with the "Done" button appearing. The fade out from the portal appears, but only after I press "Done" I get the DateRangePicker. Setting the props for input with class "DateInput__input" to disabled for mobile (in componentDidUpdate) used to work in version 4.3.0 but for versions higher than that its useless. iOS 9.3.2.
![screen shot 2017-02-13 at 8 33 40 pm](https://cloud.githubusercontent.com/assets/5099846/22897273/c8e265ac-f22b-11e6-8dbe-137dbb24cf5d.png)

**Comment by majapw** [comment]
Let's continue tracking this issue in https://github.com/airbnb/react-dates/issues/246

**Comment by rencarKYS** [comment]
i find resolve
```css
caret-color: transparent;
```
